### ISSUE TITLE
Can't run app with rdp on

### ISSUE THREAD

**Issue by Varmod** [leon-anavi/meta-weston-remote-desktop#2]
Hi,

First of all thanks for the repo, I was struggling for some time getting the weston rdp up and running and this helped a lot.

My problem is that the backend seems to be running on the fullscreen-shell and when I start an app I'm unable to see it. I've tried changing the shell in weston.ini [screen-share] to something else but that breaks the rdp and I'm no longer able to connect to my board.

How did you solve this issue for yourself?

Thanks

**Comment by leon-anavi** [comment]
Hi @Varmod,

Sorry for the late reply. I am not sure what is causing the problem you describe. It may depend of the Wayland/Weston version and specific configurations in your weston.ini.

Best regards,
Leon
